CREATE DATABASE engigyan;

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `ID` int(255) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `GMAIL` varchar(20000) NOT NULL,
  `USER_ID` varchar(20000) NOT NULL,
  `PWD` varchar(255) NOT NULL
) ENGINE=MyISAM AUTO_INCREMENT=16 DEFAULT CHARSET=latin1;

CREATE TABLE Authorised (
    `Auth_ID` int PRIMARY KEY AUTO_INCREMENT,
    `ID` int,
    FOREIGN KEY(`ID`) REFERENCES users(`ID`)
);